package com.javacodingagent.common.domain;
public enum AgentStopReason { TEST_PASSED, MAX_REPAIR_ATTEMPTS_REACHED, SAME_ERROR_REPEATED, NO_EFFECTIVE_CHANGE, UNSAFE_OPERATION_DETECTED, CONTEXT_LIMIT_REACHED, HUMAN_CONFIRMATION_REQUIRED, MODEL_DECISION_FAILED }
